window.PRINTABLE_MODEL_NAMES = new Set([
  'Absolute Batman',
  'Aaron Cash',
  'Ace',
  'Alfred Pennyworth',
  'Arkham Assistant 1',
  'Arkham Assistant 2',
  'Arkham Knight',
  'Armoured Assassin',
  'Axe Clown',
  'Bane Commander',
  'Bane Dark Knight Rises',
  'Bane Titan',
  'Bane Unleashed',
  'Barsad',
  'Barrel Clown',
  'Batgirl Classic Costume',
  'Batgirl Vampire Queen',
  'Batman 1997',
  'Batman Arkham City',
  'Batman Arkham Knight',
  'Batman Dark Knight Rises',
  'Batman Dark Knight Rises Batpod',
  'Batman Red Rain',
  'Batman The Gotham City Knight',
  'Batmobile Arkham Knight',
  'Beast Boy - Gorilla Teen Titans',
  'Beast Boy - Hawk Teen Titans',
  'Beast Boy - Human (Teen Titans)',
  'Beast Boy - Tiger Teen Titans',
  'Beat Cop',
  'Bird Classic',
  'Black Canary',
  'Blunderbuss Clown',
  'Bruce Batman Begins',
  'Bruce the Hyena',
  'Catwoman Batman Returns',
  'Catwoman Dark Knight Rises',
  'Cheshire',
  'Christmas Joker',
  'Clayface',
  'Clown Hunter',
  'Commissioner Gordon',
  'Condiment King',
  'Crazy Quilt',
  'Damien Darhk',
  'Deadshot',
  'Dementor',
  'Detective Montoya',
  'Dove',
  'Dr. Friitawa',
  'Eagly',
  'Electrocutioner',
  'Emperor Penguin',
  'Emperor Penguin Unchained',
  'Eraser',
  'Explosive Penguin',
  'Floronic Man',
  'Frank the Plant',
  'Gentleman Ghost',
  'Green Arrow (Arrow)',
  'Grumpy',
  'Guardian Monk',
  'Happy',
  'Harley Quinn (& The Boys)',
  'Chainsaw Clown',
  'Harley Quinn',
  'Harley Quinn (Arkham Asylum)',
  'Harley Quinn (BTG)',
  'Harley Quinn Arkham Knight',
  'Harley Quinn Bewitched',
  'Harley Quinn KaBoom!',
  'Harley Quinn Roller Derby',
  'Harley Thug 1',
  'Harley Thug 2',
  'Harley Thug 3',
  'Harley Thug 4',
  'Harley Thug 5',
  'Harley Thug 6',
  'Harley Thug 7',
  'Hawk',
  'Henry Ducard',
  'Huge Nightmare',
  'Hugo Strange',
  'Huntress',
  'Hypnotic',
  'Imperceptible Man',
  'Infiltrate OP',
  'Joker (Arkham Asylum)',
  'Joker (Bat-Armor)',
  'Joker (Dark Knight Rises)',
  'Joker (Explosive Arrival)',
  'Joker Titan',
  'Joker\'s Bus Driver',
  'KGBeast',
  'Killer Frost (Rebirth)',
  'Killer Frost Rebirth',
  'Killer Moth',
  'Kite-Man',
  'Lady Shiva',
  'Lark',
  'League Acolyte 1',
  'League Acolyte 2',
  'League Acolyte 3',
  'League Acolyte 4',
  'League of Shadows Ninja 1',
  'League of Shadows Ninja 2',
  'League of Shadows Ninja 3',
  'Lieutenant OP',
  'Lincoln March',
  'Little Nightmare',
  'Lobo (Paramilitary)',
  'Loose Lips',
  'Macgregor',
  'Mad Hatter',
  'Mad Hatter Arkham Knight',
  'Malicia',
  'Man-Bat',
  'Medic OP',
  'Mercenary 1',
  'Mercenary 2',
  'Minigun Penguin',
  'Miranda Tate',
  'Mr. Camera',
  'Mr. Combustible',
  'Mr. Toxic',
  'Mutated Plant 1',
  'Mutated Plant 2',
  'Mutated Plant 3',
  'Nightmare of Anger',
  'Nightmare of Demotivation',
  'Nightmare of Fear',
  'Nightmare of Insignificance',
  'Nightwing Arkham Knight',
  'Nightwing Rebirth',
  'Nyssa Al Ghul',
  'Oracle',
  'Peacemaker John Cena',
  'Penguin Elite Thug',
  'Penguin Lieutenant',
  'Penguin Thug 1',
  'Penguin Thug 2',
  'Poison Ivy',
  'Poison Ivy Arkham City',
  'Polka-Dot Man',
  'Psycho Pirate',
  'Ra\'s al Ghul',
  'Ra\'s Al Ghul Acolyte',
  'Rabid Plant 1',
  'Rabid Plant 2',
  'Raven',
  'Raven Trigon\'s Daughter',
  'Rebel Masked Assassin 1',
  'Rebel Masked Assassin 2',
  'Rebel Monk',
  'Red Hood The Outlaw',
  'Red Robin',
  'Robin 1997',
  'Robin Classic',
  'Rocket Launcher Penguin',
  'Roller Derby Thug 1',
  'Roller Derby Thug 2',
  'Roller Derby Thug 3',
  'Roller Derby Thug 4',
  'Scarecrow (The Worst Nightmare)',
  'Scarecrow Arkham Asylum',
  'Shadow Armored Assassin',
  'Smash',
  'Solomon Grundy',
  'Starfire Teen Titans',
  'Street Demonz 1',
  'Street Demonz 2',
  'Street Demonz 3',
  'Street Demonz 4',
  'Street Jester 1',
  'Street Jester 2',
  'SWAT QRT 1',
  'SWAT QRT 2',
  'SWAT QRT 3',
  'Talia Rebirth',
  'Ted Hunter',
  'The Heretic',
  'The Penguin (Burgess Meredith)',
  'The Penguin Arkham City',
  'The Penguin Crime Lord Rising',
  'The Penguin Danny DeVito',
  'The Penguin New 52',
  'The Penguin Penguin\'s Duck',
  'Two-Face Arkham City',
  'Ubu',
  'Warden Sharp',
  'Wonder Girl',
]);

window.PRINTABLE_MODEL_KEYS = new Set([
  'Batman||Bruce Wayne||40mm',
  'Batman||Thomas Wayne||40mm',
  'Joker||Unknown||40mm / 60mm',
  'Unknown||Cassandra Cain||30mm',
]);

window.PRINTABLE_MODEL_IMAGE_KEYS = new Set([
  'RobinDamian.png',
]);
